version: '3'
# docker rm $(docker ps -a -q) && docker volume prune -f
services:
  postgres:
    image: postgis/postgis
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: car_life_api
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting
      SHARED_PRELOAD_LIBRARIES: pg_cron
    ports:
      - '5432:5432'
    volumes:
      - './config/sql/:/docker-entrypoint-initdb.d/'
      - './postgres-data:/var/lib/postgresql/data'

  tarantool:
    image: tarantool/tarantool
    environment:
      TARANTOOL_USER_NAME: admin
      TARANTOOL_USER_PASSWORD: pass
    command: tarantool /opt/tarantool/app.lua
    ports:
      - "3301:3301"
    volumes:
      - './tarantool-data:/var/lib/tarantool'
      - './config/lua/:/opt/tarantool/'
    restart: always
