basePath: /api/v1
definitions:
  models.Club:
    properties:
      avatar:
        type: string
      description:
        type: string
      events_count:
        type: integer
      id:
        type: integer
      name:
        type: string
      participants_count:
        type: integer
      tags:
        items:
          type: string
        type: array
    required:
    - avatar
    - description
    - events_count
    - id
    - name
    - participants_count
    - tags
    type: object
  models.CreateClubRequest:
    properties:
      avatar:
        type: string
      description:
        type: string
      name:
        type: string
      tags:
        items:
          type: string
        type: array
    required:
    - avatar
    - description
    - name
    - tags
    type: object
  models.CreateEventRequest:
    properties:
      avatar:
        type: string
      club_id:
        type: integer
      description:
        type: string
      event_date:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      name:
        type: string
    required:
    - avatar
    - club_id
    - description
    - event_date
    - latitude
    - longitude
    - name
    type: object
  models.Event:
    properties:
      avatar:
        type: string
      club:
        $ref: '#/definitions/models.Club'
      description:
        type: string
      event_date:
        type: string
      id:
        type: integer
      latitude:
        type: number
      longitude:
        type: number
      name:
        type: string
    required:
    - avatar
    - club
    - description
    - event_date
    - id
    - latitude
    - longitude
    - name
    type: object
  models.Tag:
    properties:
      id:
        type: integer
      name:
        type: string
    required:
    - id
    - name
    type: object
  utils.Error:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for CarLife application
  title: Swagger Example API
  version: "1.0"
paths:
  /club/create:
    post:
      consumes:
      - application/json
      description: Handler for creating a club
      parameters:
      - description: Club
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.CreateClubRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Club'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: create a club
      tags:
      - Clubs
  /clubs:
    get:
      consumes:
      - application/json
      description: Handler for getting clubs list
      parameters:
      - description: IdGt
        in: query
        name: IdGt
        type: integer
      - description: IdLte
        in: query
        name: IdLte
        type: integer
      - description: Limit
        in: query
        name: Limit
        type: integer
      - description: Query
        in: query
        name: Query
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Club'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: get clubs list
      tags:
      - Clubs
  /clubs/{id}:
    get:
      consumes:
      - application/json
      description: Handler for getting a club by id
      parameters:
      - description: Club ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Club'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: get club by id
      tags:
      - Clubs
  /clubs/{id}/upload:
    post:
      consumes:
      - multipart/form-data
      description: Handler for uploading a club's avatar
      parameters:
      - description: Club ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Club'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: upload avatar for club
      tags:
      - Clubs
  /clubs/tags:
    get:
      consumes:
      - application/json
      description: Handler for getting tags list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Tag'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: get tags list
      tags:
      - Clubs
  /event/create:
    post:
      consumes:
      - application/json
      description: Handler for creating an event
      parameters:
      - description: Event
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.CreateEventRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: create an event
      tags:
      - Events
  /events:
    get:
      consumes:
      - application/json
      description: Handler for getting events list
      parameters:
      - description: IdGt
        in: query
        name: IdGt
        type: integer
      - description: IdLte
        in: query
        name: IdLte
        type: integer
      - description: Limit
        in: query
        name: Limit
        type: integer
      - description: Query
        in: query
        name: Query
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Event'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: get events list
      tags:
      - Events
  /events/{id}:
    get:
      consumes:
      - application/json
      description: Handler for creating an event
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: get event by id
      tags:
      - Events
  /events/{id}/upload:
    post:
      consumes:
      - multipart/form-data
      description: Handler for creating an event
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: upload avatar for event
      tags:
      - Events
swagger: "2.0"
