basePath: /api/v1
definitions:
  models.CarCard:
    properties:
      avatar_url:
        type: string
      body:
        type: string
      brand:
        type: string
      date:
        type: string
      description:
        type: string
      engine:
        type: string
      horse_power:
        type: string
      id:
        type: integer
      model:
        type: string
      name:
        type: string
      owner_id:
        type: integer
    required:
    - avatar_url
    - body
    - brand
    - date
    - description
    - engine
    - horse_power
    - id
    - model
    - name
    - owner_id
    type: object
  models.CarRequest:
    properties:
      body:
        type: string
      brand:
        type: string
      date:
        type: string
      description:
        type: string
      engine:
        type: string
      horsePower:
        type: string
      model:
        type: string
      name:
        type: string
    type: object
  models.Club:
    properties:
      avatar:
        type: string
      club_events:
        items:
          $ref: '#/definitions/models.EventCard'
        type: array
      club_garage:
        items:
          $ref: '#/definitions/models.CarCard'
        type: array
      description:
        type: string
      events_count:
        type: integer
      id:
        type: integer
      name:
        type: string
      owner_id:
        type: integer
      participants_count:
        type: integer
      tags:
        items:
          type: string
        type: array
    required:
    - avatar
    - club_events
    - club_garage
    - description
    - events_count
    - id
    - name
    - owner_id
    - participants_count
    - tags
    type: object
  models.ClubCard:
    properties:
      avatar:
        type: string
      id:
        type: integer
      name:
        type: string
      participants_count:
        type: integer
      tags:
        items:
          type: string
        type: array
    required:
    - avatar
    - id
    - name
    - participants_count
    - tags
    type: object
  models.CreateClubRequest:
    properties:
      avatar:
        type: string
      description:
        type: string
      name:
        type: string
      tags:
        items:
          type: string
        type: array
    required:
    - avatar
    - description
    - name
    - tags
    type: object
  models.CreateEventRequest:
    properties:
      avatar:
        type: string
      club_id:
        type: integer
      description:
        type: string
      event_date:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      name:
        type: string
    required:
    - avatar
    - club_id
    - description
    - event_date
    - latitude
    - longitude
    - name
    type: object
  models.Event:
    properties:
      avatar:
        type: string
      club:
        $ref: '#/definitions/models.Club'
      description:
        type: string
      event_date:
        type: string
      id:
        type: integer
      latitude:
        type: number
      longitude:
        type: number
      name:
        type: string
      participants_count:
        type: integer
    required:
    - avatar
    - club
    - description
    - event_date
    - id
    - latitude
    - longitude
    - name
    - participants_count
    type: object
  models.EventCard:
    properties:
      avatar:
        type: string
      event_date:
        type: string
      id:
        type: integer
      latitude:
        type: number
      longitude:
        type: number
      name:
        type: string
    required:
    - avatar
    - event_date
    - id
    - latitude
    - longitude
    - name
    type: object
  models.LoginRequest:
    properties:
      vkid:
        type: integer
    type: object
  models.SignUpRequest:
    properties:
      avatarUrl:
        type: string
      description:
        type: string
      garage:
        items:
          $ref: '#/definitions/models.CarRequest'
        type: array
      name:
        type: string
      surname:
        type: string
      tags:
        items:
          type: string
        type: array
      vkid:
        type: integer
    type: object
  models.Tag:
    properties:
      id:
        type: integer
      name:
        type: string
    required:
    - id
    - name
    type: object
  models.User:
    properties:
      avatar_url:
        type: string
      description:
        type: string
      garage:
        items:
          $ref: '#/definitions/models.CarCard'
        type: array
      name:
        type: string
      own_clubs:
        items:
          $ref: '#/definitions/models.ClubCard'
        type: array
      participant_clubs:
        items:
          $ref: '#/definitions/models.ClubCard'
        type: array
      participant_events:
        items:
          $ref: '#/definitions/models.EventCard'
        type: array
      surname:
        type: string
      tags:
        items:
          type: string
        type: array
      vkid:
        type: integer
    required:
    - avatar_url
    - description
    - garage
    - name
    - own_clubs
    - participant_clubs
    - participant_events
    - surname
    - tags
    - vkid
    type: object
  utils.Error:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for CarLife application
  title: Swagger Example API
  version: "1.0"
paths:
  /club/create:
    post:
      consumes:
      - application/json
      description: Handler for creating a club
      parameters:
      - description: Club
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.CreateClubRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Club'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: create a club
      tags:
      - Clubs
  /clubs:
    get:
      consumes:
      - application/json
      description: Handler for getting clubs list
      parameters:
      - description: IdGt
        in: query
        name: IdGt
        type: integer
      - description: IdLte
        in: query
        name: IdLte
        type: integer
      - description: Limit
        in: query
        name: Limit
        type: integer
      - description: Query
        in: query
        name: Query
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ClubCard'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: get clubs list
      tags:
      - Clubs
  /clubs/{id}:
    get:
      consumes:
      - application/json
      description: Handler for getting a club by id
      parameters:
      - description: Club ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Club'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: get club by id
      tags:
      - Clubs
  /clubs/{id}/upload:
    post:
      consumes:
      - multipart/form-data
      description: Handler for uploading a club's avatar
      parameters:
      - description: Club ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Club'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: upload avatar for club
      tags:
      - Clubs
  /clubs/tags:
    get:
      consumes:
      - application/json
      description: Handler for getting tags list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Tag'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: get tags list
      tags:
      - Clubs
  /event/create:
    post:
      consumes:
      - application/json
      description: Handler for creating an event
      parameters:
      - description: Event
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.CreateEventRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: create an event
      tags:
      - Events
  /events:
    get:
      consumes:
      - application/json
      description: Handler for getting events list
      parameters:
      - description: IdGt
        in: query
        name: IdGt
        type: integer
      - description: IdLte
        in: query
        name: IdLte
        type: integer
      - description: Limit
        in: query
        name: Limit
        type: integer
      - description: Query
        in: query
        name: Query
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.EventCard'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: get events list
      tags:
      - Events
  /events/{id}:
    get:
      consumes:
      - application/json
      description: Handler for creating an event
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: get event by id
      tags:
      - Events
  /events/{id}/upload:
    post:
      consumes:
      - multipart/form-data
      description: Handler for creating an event
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: upload avatar for event
      tags:
      - Events
  /garage/{id}/upload:
    post:
      consumes:
      - multipart/form-data
      description: Handler for creating an event
      parameters:
      - description: Car ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: upload avatar for car
      tags:
      - Users
  /login:
    post:
      consumes:
      - application/json
      description: Handler for signing up new user
      parameters:
      - description: User
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "401":
          description: ""
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: login user
      tags:
      - Users
  /me:
    get:
      consumes:
      - application/json
      description: Handler for getting a user by id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: get user by id
      tags:
      - Users
  /signup:
    post:
      consumes:
      - application/json
      description: Handler for signing up new user
      parameters:
      - description: User
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: sign uo new user
      tags:
      - Users
  /user/{id}:
    get:
      consumes:
      - application/json
      description: Handler for getting a user by id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: get user by id
      tags:
      - Users
swagger: "2.0"
